- src/lib.rs
I added some of the missing event codes from input-event-codes.h.  Their
omission causes the library to panic with some input devices.
> Missing constants for relative axes

- Cargo.toml
- README.md
- src/lib.rs
- src/raw.rs
nix 0.9's ioctl macro works with buffers now.
eviocgname/eviocgphys/eviocguniq do not return the number of bytes on FreeBSD, just zero. So let CStr handle the null termination.
> Update nix to 0.9, support FreeBSD

- src/lib.rs
Hi,
I already asked in issue #20 why the multitouch axes were intentionally ignored when requesting axes.
The changes, I noted there, were added to [libremarkable](https://github.com/canselcik/libremarkable/) (a library to use the hardware of the [reMarkable](https://remarkable.com/) Gen 1 and working on Gen 2) so we can get the size of the multitouch screen for any device generation and do not need to hardcode the sizes which will make future updates easier.
Now, it turned out, that we can't just refer to my [fork](https://github.com/LinusCDE/evdev/) and publish this on crates.io ([related discussion that cause this PR](https://github.com/canselcik/libremarkable/commit/6f420e4e193b7767c52452a9241329960be9b9ab#commitcomment-45410368)). (I initially thought, waiting on the issue to get …
> Force to request absinfo also onmultitouch axes

- .gitignore
- Cargo.toml
- src/lib.rs
- src/raw.rs
Updates `bitflags` to 1.2, `fixedbitset` to 1.3.2, and most critically updates `nix` to 0.19.
I've removed the manual casts to `c_ulong` in `eviocgbit` and `eviocgabs` because `request_code_read!` already contains platform-specific logic to ensure the request code type matches the ioctl call type on the target OS.
More generally addresses https://github.com/emberian/evdev/issues/22
> Update dependencies and fix cross-compatibility issues

- Cargo.toml
- src/lib.rs
- src/raw.rs
- src/scancodes.rs
- src/tests.rs
Closes https://github.com/emberian/evdev/issues/12 and https://github.com/emberian/evdev/issues/14
* Clean up quite a bit of unnecessary `unsafe` code, including direct calls to `clock_gettime`, `open`, and `read`, among others.
* Remove macros that hide `unsafe`. These were difficult to read and audit.
* Use `std::fs::File` to open and retain `/dev/event/*`. Eliminates the need for a custom Drop impl and improves unwind safety.
* Eliminate all use of `transmute`. Specifically there was a wildly unsafe transmute to the `Key` enum that resulted in undefined behavior. Replaced with safe calls to `num_traits::FromPrimitive`. Also removed or replaced transmute used for pointer and slice casts.
* `raw::eviocgbit` and `raw::eviocgabs` now accept mut slices instead of raw pointers (to match the …
> Fix a bunch of unsoundness, and clean up some stuff

- Cargo.toml
- src/device_state.rs
- src/lib.rs
- src/raw_stream.rs
- src/sync_stream.rs
This exposes a non-cached way to directly access the kernel keys/switches/values. It also renames things a bit to make it clear that no external API apart from `fetch_events` will have any side effects on the internal sync state.
I'm pretty sure the documentation stating that the cached_state is updated automatically is incorrect-- the timestamps were certainly not being updated in real time. We should take another pass through that.
> Ergonomics

- src/attribute_set.rs
- src/lib.rs
- src/scancodes.rs
rc keymaps list keycodes as strings. These need to be converted to
numeric keycodes before the keymap can be loaded. So, add a function
to convert a string to keycode.
Signed-off-by: Sean Young <sean@mess.org>
> Convert string to key code

- src/sync_stream.rs
Otherwise, calling next() always returned the same event from compensate_events, because the previous state was never updated.
Fixes #53
> Update previous state during compensation.

- examples/blink_keyboard_leds.rs
- src/raw_stream.rs
- src/sync_stream.rs
Some devices (such as keyboards) support writing events through event nodes to
turn LEDs off and on, play sound effects or play ff effects.
This commits adds the appropriate methods in the public API of the crate.
I also added an example to showcase the new functionality.
> Add `Device::send_event` and `RawDevice::send_event`.

- examples/_pick_device.rs
- src/lib.rs
- src/raw_stream.rs
- src/sync_stream.rs
I am working on a layering keymapper program and would like to use `evdev::enumerate` to help the user discover what keyboard devices are available for remapping. Currently it's not possible to get that information from a given `Device` instance. This PR makes that information available by preserving the system path used to instantiate each `Device` object.
> enable getting system path for Device

- examples/virtual_joystick.rs
- src/lib.rs
- src/sys.rs
- src/uinput.rs
I wasn't really sure where to place `UinputAbsSetup` struct... perhaps `src/uinput.rs`?
And listing out all getters for fields of both structs that I added looks like a hack but I couldn't think of a better way.
> Add all bits and pieces for absolute axes in uinput and an example

- src/raw_stream.rs
Currently it is not possible to get a mutable reference to the `RawDevice` from an `EventStream`, which is needed for `RawDevice::ungrab()`. This implements `EventStream::device_mut()` to return a mutable reference.
> implement EventStream::device_mut()

- Cargo.toml
- src/error.rs
- src/lib.rs
This uses the `thiserror` crate to implement a separate `Error` type to prepare for PR #74.
> implement Error type

- Cargo.toml
- src/sys.rs
- src/uinput.rs
This addresses issue #70 by:
- Implementing the ui_get_sysname ioctl.
- Using the aforementioned ioctl to implement `VirtualDevice::get_syspath()` function, which returns the syspath of the form `/sys/devices/virtual/input/inputX` for the virtual device.
- Adding both a synchronous and asynchronous version of `VirtualDevice::enumerate_dev_nodes()` depending on the `tokio` feature flag that essentially yields an iterator over the devices nodes of the form `/dev/input/eventX` that correspond to the virtual device.
> implement get_sys_path() and dev node iterator for virtual devices

- Cargo.toml
- src/attribute_set.rs
- src/lib.rs
This PR adds serialization/deserialization support using serde for the constants defined using the `evdev_enum!` macro, and in addition derives `Serialize` and `Deserialize` for `InputEventKind`.
The changelog is as follows:
- Add `serde` as an optional dependency.
- Add `paste` to help out with the macro logic in the `evdev_enum!` macro.
- Implement a custom serializer and deserializer in the `evdev_enum!` macro for `$t`.
- Derive `Serialize` and `Deserialize` for `InputEventKind`.
> Implement serde support

- CHANGELOG.md
- Cargo.toml
- README.md
This PR mostly prepares everything for evdev 0.11.6 with all the new goodies that landed upstream:
- Update the example section in the README, since we have plenty of examples now.
- Add a CHANGELOG.md inspired by the one from Cargo.
- Add a link to the CHANGELOG.md from the README.
- Release evdev 0.11.6 (I am guessing we need @coolreader18 to publish this on Cargo once done).
This also addresses issue #70.
> Release 0.11.6

- CHANGELOG.md
- src/uinput.rs
This PR fixes an issue where the `DevNodesBlocking` iterator blocks indefinitely when the underlying `ReadDir` iterator is exhausted. Instead we check if the underlying `ReadDir` iterator actually has an entry and return `None` if the iterator is exhausted to indicate to the caller of `DevNodesBlocking::next()` that the iterator has been exhausted.
> fix DevNodesBlocking iterator to not block indefinitely when exhausted

- CHANGELOG.md
- src/lib.rs
- src/raw_stream.rs
- src/sync_stream.rs
This is mostly a collection of small improvements:
- PR #73 missed the `EventStream` implementation in `sync_stream.rs`. So this adds `EventStream::device_mut()` there too.
- Implement `FFEffect::id()` as an accessor to be able to grab the ID. It can be useful when creating a virtual device that almost directly exposes the force feedback effects of another actual device.
- Missing public export for `FFEffect` from the crate root.
- Add some documentation for `FFEffect` while I am at it.
> Improve FFEffect and add EventStream::device_mut().

- src/sync_stream.rs
- src/uinput.rs
- `EventStream::device_mut()` needs a mutable reference to `self`.
- Remove an unused import in `src/uinput.rs`.
> device_mut needs a mutable reference of self and remove unused import

- .github/workflows/rust.yml
- src/lib.rs
There exists what looks like a stale Travis CI manifest, but nothing is using it. Let's use GH Actions to make sure PRs build cleanly with standard formatting, and pass tests.
> Create GH actions builder

- Cargo.toml
- examples/_pick_device.rs
- examples/evtest_nonblocking.rs
- src/compat.rs
- src/compat/non_linux.rs
- src/constants.rs
- src/device_state.rs
- src/ff.rs
- src/inputid.rs
- src/lib.rs
- src/raw_stream.rs
- src/scancodes.rs
- src/sync_stream.rs
- src/sys.rs
- src/uinput.rs
Resolves https://github.com/emberian/evdev/issues/65.
I was able to use some basic CI hackery to ensure this at least compiles on FreeBSD 13.1, but as GH Actions doesn't have native support for that platform it's unlikely we will add those tests to the standard CI set.
> FreeBSD compatibility

- LICENSE-APACHE
- LICENSE-MIT
This PR addresses #68 by adding LICENSE-APACHE and LICENSE-MIT to the repository. This will show up on Github as: " Apache-2.0, MIT licenses found" (on the right side of the repository page).
> add Apache and MIT license

- src/uinput.rs
Avoid re-implementing `poll_fn` in `src/uinput.rs` by importing the existing `poll_fn` implementation from `src/raw_stream.rs` instead.
> use raw_stream::poll_fn in uinput.rs instead

- src/lib.rs
> Fix build on 32 bit arm where tv_sec (time_t) is i32

- src/uinput.rs
This PR is similar to #79 but for the asynchronous variant `DevNodes` instead. Basically, `next_entry()` is rewritten such that when the underlying `next_entry()` is exhausted, it returns `Ok(None)` to indicate that the iterator has been exhausted.
> avoid loop in DevNodes::next_entry() and return Ok(None) when exhausted

- examples/virtual_ff.rs
- examples/virtual_joystick.rs
- examples/virtual_keyboard.rs
This PR extends the virtual device examples to use the `enumerate_dev_nodes_blocking()` function to show the path of the virtual device, such that you don't have to guess the path when trying to test the examples with tools such as `evtest` and `fftest`.
> examples: show the device path of the virtual device

- src/raw_stream.rs
- src/sync_stream.rs
Implement `RawDevice::max_ff_effects()` and `Device::max_ff_effects()` to report the maximum number of force feedback effects that can be played simultaneously by the device.
> report the maximum number of simultaneous FF effects supported

- Cargo.toml
- src/lib.rs
- src/raw_stream.rs
- src/sync_stream.rs
- src/uinput.rs
Should cause `docs.rs` to build documentation for items behind feature flags, and to label them with the associated feature flags.
Uses the [`--all-features`](https://doc.rust-lang.org/cargo/reference/features.html#command-line-feature-options) cargo option and the unstable [`doc_auto_cfg`](https://doc.rust-lang.org/rustdoc/unstable-features.html#doc_auto_cfg-automatically-generate-doccfg) feature to achieve this. Places the `doc_auto_cfg` feature behind a cfg flag so that it's only used when running on `docs.rs`.
Includes a plan accounting for the [(currently) expected stabilization path for `doc_auto_cfg`](https://github.com/rust-lang/rust/pull/100883).
Unfortunately, I lack the setup required to run `docs.rs` locally, so I cannot test the `docs.rs`-specific configuration options at …
> Document items behind feature flags

- src/uinput.rs
fixes #101 
adds a `with_msc` method to VirtualDeviceBuilder
> Add EV_MSC support to VirtualDeviceBuilder

- src/uinput.rs
fixes #104 
adds a with_properties method to VirtualDeviceBuilder in uinput.rs
> Add device properties support to VirtualDeviceBuilder

- .github/workflows/rust.yml
Extend the Github workflow to set up QEMU and the Rust toolchain, and then build/test evdev for various targets (aarch64, arm and i686).
This way we can also easily catch issues like #95 and #96 and also #82.
> Extend Github action to cross-compile to aarch64/arm/i686 for Linux

- src/inputid.rs
Many modern peripherals create multiple `/dev/input/eventXX` files, which all share the same product and vendor id. 
I want to group all `Device`s from the same physical device and store different physical devices in a HashMap.
```rust
let mut device_map: HashMap<InputId, Vec<Device>> = HashMap::new();
for device in evdev::enumerate().map(|t| t.1) {
let value = device_map.entry(device.input_id()).or_insert(Vec::new());
value.push(device);   
}
```
> derive Hash, Eq, PartialEq from InputId

- src/constants.rs
I want to match incoming events against a collection of user defined events. Currently that is not very convenient because none of the newtypes in `constants.rs` implement the Hash trait.
```rust
let mut d = Device::open("/dev/input/event0").unwrap();
let hat_switches: HashSet<AbsoluteAxisType> = (0x10..=0x17).into_iter().map(AbsoluteAxisType).collect();
loop {
for ev in d.fetch_events().unwrap() {
if let InputEventKind::AbsAxis(axis) = ev.kind() {
if hat_switches.contains(&axis) {
println!("got a Hat event, converting to button event!");
todo!()
}
}
println!("{:?}", ev);
}
}
```
Also given that these newtypes already implement Eq and PartialEq I would assume that one might use them as a hash.
> derive Hash trait for input-event-codes.h newtypes

- examples/blink_keyboard_leds.rs
- examples/evtest.rs
- examples/evtest_nonblocking.rs
- examples/force_feedback.rs
- examples/virtual_ff.rs
- src/raw_stream.rs
- src/sync_stream.rs
Currently there is no way to get a `AbsInfo` object from the library. Sure, there is the `get_abs_state()` method, but that only returns a slice of `[input_absinfo,_]` and it is not at all clear that one needs to index that slice with the correct code (i.e. ABS_X) to get the corresponding absinfo.
Current API:
```rust
let code = AbsoluteAxisType::ABS_X.0 as usize;
let raw_absinfo = device.get_abs_state()?;
let absinfo = AbsInof::new(
raw_absinfo[code].value,
raw_absinfo[code].minimum,
raw_absinfo[code].maximum,
raw_absinfo[code].fuzz,
raw_absinfo[code].flat,
raw_absinfo[code].resolution,
);
// be aware: we get a valid absinfo, even if the device does not support 
// AbsoluteAxisType::ABS_X, or does not support EV_ABS
```
Proposed API:
```rust
let absinfo = device
.get_absinfo()
.unwrap() …
```
> implement Device::get_absinfo()

- examples/virtual_mouse.rs
An interesting point to note is that up/down between mouse movement and scrolling have opposite signs.
Another interesting point is that the mouse movements were not registering with the 2s sleeps that were used in the virtual keyboard example, so a shorter sleep is used. Perhaps my desktop environment is, for reasons unknown to me, ignoring the first mouse event after a certain period of no mouse events.
> add mouse example

- Cargo.toml
- src/lib.rs
Adds some convenient traits for the wrapper types.
The change was motivated mostly because `Device::get_abs_state` returns the raw `input_absinfo` while the constructor function `UInputAbsSetup::new` (necessary for absolute axes in the `VirtualDeviceBuilder`) needs an `AbsInfo`, which currently has to be constructed via deconstructing the raw type and invocating the `new` function.
I think the other traits are convenient to have as well, as the raw types all implement `Debug`, `PartialEq`,  `Eq` and `Hash` and to be consistent with the wrapper `InputEvent`.
I guess a dependency implicitly enabled `extra_traits` for `libc`, so it compiled without the extra feature in the `Cargo.toml`. I added it though for the sake of completeness and correctness
> Add more trait implementations for Wrapper types (From, Eq, PartialEq, Debug, AsRef, Hash)

- tests/virtual_device.rs
Previously the test used BTN_DPAD_UP as a test code but the virtual device is configured to only have the KEY_ESC code. This causes the test to fail on some systems.
> update test_virtual_device_actually_emits to use KEY_ESC

- src/raw_stream.rs
- src/sync_stream.rs
In some use-cases the process initializing the evdev device doesn't have the permissions to open the file - instead the fd is handed to it via e.g. DBus. This is the case for Wayland compositors using logind.
Expose Device::from_fd() as public function so we can initialize a device purely from the fd.
> Make Device::from_fd() public

- src/uinput.rs
This reverts commit d0231e3c626316b18de59eec5d1ff8a344d94c9e.
resolves device pathname regression, issue #129
> Revert "use entry.path() and simplify starts_with() code"

- src/raw_stream.rs
- src/sync_stream.rs
Fixes #157.
1. Adds `impl Drop for Device` to call `Device::ungrab()` on drop.
2. Adds `Device::is_grabbed() -> bool` and `RawDevice::is_grabbed() -> bool` to allow inspection of current grab state.
3. Derives `Debug` for `Device`.
> Device enhancements: derive Debug, impl Drop for Device to call Device::ungrab() on drop, add Device::is_grabbed()
